# Generated by Django 3.0.6 on 2020-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_resume',
            field=models.FileField(blank=True, upload_to='resume_default'),
        ),
    ]
